# Cargo config file.

# Environments variables set for all `cargo ...` commands.
[env]

# Scope down tracing, to filter out external lib tracing.
RUST_LOG = "axum_tut=debug"

# Service Environment Variables
# IMPORTANT:
#   For cargo commands only.
#   For deployed env, should be managed by container
#   (e.g., Kubernetes).

## -- Secrets
# Keys and passwords below are for localhost dev ONLY.
# e.g., "welcome" type of passwords.
# i.e., Encryption not needed.

SERVICE_DB_URL = "postgres://app_user:dev_only_pwd@localhost/app_db"
SERVICE_PWD_KEY = "XzHKbfaXhChEfxHiUs1lsTNO3SAWy_6MshLQ4YtC4BvDVjoJUMshrIS-XyS4Bi51WP6GE8ONOXVMY39ag4PHGg"
SERVICE_TOKEN_KEY = "PAXMuGhc9ZZcf0xsWySYob6gcWth_ka2Eo0ur9zXidzUYvfKpen-0O5qKmk-Om2_VIV_1s4tALUZeZICIUW_WQ"
SERVICE_TOKEN_DURATION_SEC = "1800"
## -- ConfigMap

SERVICE_WEB_FOLDER = "web-folder/"
